INSERT INTO Book (title, author) VALUES ('The Kite Runner', 'Khaled Hosseini');
INSERT INTO Book (title, author) VALUES ('The Book Thief', 'Markus Zusak');
INSERT INTO Book (title, author) VALUES ('Jane Eyre', 'Charlotte Bronte');
INSERT INTO Book (title, author) VALUES ('Animal Farm', 'George Orwell');
INSERT INTO Book (title, author) VALUES ('Fahrenheit 451', 'Ray Bradbury');
INSERT INTO Book (title, author) VALUES ('Charlotte''s Web', 'E. B. White');
INSERT INTO Book (title, author) VALUES ('Frankenstein', 'Mary Shelley');
INSERT INTO Book (title, author) VALUES ('Of Mice and Men', 'John SteinBeck');
INSERT INTO Book (title, author) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald');
INSERT INTO Book (title, author) VALUES ('A Brief History Of Time', 'Stephen Hawking');
INSERT INTO Book (title, author) VALUES ('The Hunger Games', 'Suzanne Collins');
INSERT INTO Book (title, author) VALUES ('Pride and Prejudice', 'Jane Austen');
INSERT INTO Book (title, author) VALUES ('To Kill a Mocking Bird', 'Harper Lee');
INSERT INTO Book (title, author) VALUES ('Gone with the Wind', 'Margaret Mitchell');
